from models import Department, Employee, Role, engine, db_session

Department.__table__.create(engine)
Employee.__table__.create(engine)
Role.__table__.create(engine)
s=db_session()
e=Department(name='Engineering')
s.add(e)
h=Department(name='HR')
s.add(h)
m=Role(name='manager')
s.add(m)
ee=Role(name='engineer')
s.add(ee)
p=Employee(name='Peter', department=e, role=ee)
s.add(p)
t=Employee(name='Tracy',department=h,role=m)
s.add(t)
s.commit()
